/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.23.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  owner?: string | null;
}
export type ExecuteMsg = {
  new_entry: {
    description: string;
    priority?: Priority | null;
  };
} | {
  update_entry: {
    description?: string | null;
    id: number;
    priority?: Priority | null;
    status?: Status | null;
  };
} | {
  delete_entry: {
    id: number;
  };
} | {
  transfer_owner_ship: {
    new_owner: string;
  };
};
export type Priority = "None" | "Low" | "Medium" | "High";
export type Status = "Todo" | "InProgress" | "Done" | "Cancelled";
export type QueryMsg = {
  query_entry: {
    id: number;
  };
} | {
  query_list: {
    limit?: number | null;
    start_after?: number | null;
  };
};
export interface EntryResponse {
  description: string;
  id: number;
  priority: Priority;
  status: Status;
}
export interface ListResponse {
  entries: Entry[];
}
export interface Entry {
  description: string;
  id: number;
  priority: Priority;
  status: Status;
  [k: string]: unknown;
}